name: rallytics
description: "A new Flutter project."
publish_to: 'none'

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.1.0+1

environment:
  sdk: ^3.8.1

# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`.
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_auth: ^5.7.0
  firebase_core: ^3.15.2
  firebase_crashlytics: ^4.3.10
  injectable: ^2.5.0
  flutter_bloc: ^9.1.1
  freezed: ^2.5.8
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.4
  get_it: ^8.0.3
  injectable_generator: ^2.7.0
  bloc_test: ^10.0.0
  mockito: ^5.4.6
  intl: ^0.20.2
  flutter_localization: ^0.3.3
  firebase_analytics: ^11.6.0
  flutter_launcher_icons: ^0.14.4
  google_fonts: ^6.2.1
  shared_preferences: ^2.5.3
  go_router: ^16.0.0
  font_awesome_flutter: ^10.8.0
  flutter_svg: ^2.2.0
  google_sign_in: ^7.1.1
  flutter_facebook_auth: ^6.0.4
  dio: ^5.9.0
  cloud_firestore: ^5.6.12
  cached_network_image: ^3.4.1
  fake_cloud_firestore: ^3.1.0
  shimmer_animation: ^2.2.2
  flutter_stripe: ^11.5.0
  http_mock_adapter: ^0.6.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.9

flutter:
  generate: true
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
flutter_intl:
  enabled: true
