// Mocks generated by Mockito 5.4.6 from annotations
// in rallytics/test/features/live_score/presentation/bloc/live_score_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:rallytics/core/usecases/usecase.dart' as _i5;
import 'package:rallytics/features/live_score/domain/entities/live_match_entity.dart'
    as _i4;
import 'package:rallytics/features/live_score/domain/usecases/get_live_scores_usecase.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [GetLiveScoresUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetLiveScoresUseCase extends _i1.Mock
    implements _i2.GetLiveScoresUseCase {
  MockGetLiveScoresUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<List<_i4.LiveMatchEntity>> call(_i5.NoParams? params) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i3.Stream<List<_i4.LiveMatchEntity>>.empty(),
          )
          as _i3.Stream<List<_i4.LiveMatchEntity>>);
}
