name: Android Build PROD (Release)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-android-debug:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java JDK 21
        uses: actions/setup-java@v4
        id: setup_java
        with:
          distribution: 'zulu'
          java-version: '21'
      
      - name: Set JAVA_HOME
        run: echo "JAVA_HOME=${{ steps.setup_java.outputs.path }}" >> $GITHUB_ENV

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.7'
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Create Firebase Options file from Base64 secret
        run: echo "${{ secrets.FIREBASE_OPTIONS }}" | base64 --decode > lib/firebase_options_prod.dart

      - name: Create 'prod' flavor directory for google-services.json
        run: mkdir -p android/app/src/prod

      - name: Create google-services.json from Base64 secret
        run: echo "${{ secrets.GOOGLE_SERVICES_JSON }}" | base64 --decode > android/app/src/prod/google-services.json

      - name: Generate generated files
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Decode Keystore
        run: echo "${{ secrets.PROD_KEYSTORE_BASE64 }}" | base64 --decode > android/app/upload-keystore.jks
      
      - name: Build Android App Bundle PROD (Release)
        run: flutter build appbundle --release --flavor prod -t lib/main_prod.dart
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.PROD_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.PROD_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.PROD_STORE_PASSWORD }}
        
      - name: Upload App Bundle artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-aab
          path: build/app/outputs/bundle/prodRelease/app-prod-release.aab