name: Android Build (Debug)

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main
  workflow_dispatch:

jobs:
  build-android-debug:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java JDK 17
        uses: actions/setup-java@v4
        id: setup_java
        with:
          distribution: 'zulu'
          java-version: '17'
      
      - name: Set JAVA_HOME
        run: echo "JAVA_HOME=${{ steps.setup_java.outputs.path }}" >> $GITHUB_ENV

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.7'
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Create Firebase Options file from Base64 secret
        run: echo "${{ secrets.FIREBASE_OPTIONS }}" | base64 --decode > lib/firebase_options.dart

      - name: Generate generated files
        run: flutter pub run build_runner build --delete-conflicting-outputs
      
      - name: Build Android APK (Debug)
        run: flutter build apk --debug
        
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: build/app/outputs/flutter-apk/app-debug.apk